use_frameworks!

platform :ios, '9.0'

target 'Tsunami_Test_Git_App_Example' do
  pod 'Tsunami_Test_Git_App', :path => '../'

  target 'Tsunami_Test_Git_App_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
